[package]
name = "benbot-rs"
version = "0.1.0"
authors = ["Ben Lepsch <blepsch@gmail.com"]
edition = "2024"

[dependencies]
poise = "0.6.1"
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }
rand = "0.9.0"
