[package]
name = "benbot-rs"
version = "0.1.0"
authors = ["Ben Lepsch <blepsch@gmail.com"]
edition = "2024"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
