on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: type=registry,ref=ghcr.io/benlepsch/benbot-rs:${{ needs.create-tag.outputs.tag }}
          cache-to: type=inline
          tags: |
            ghcr.io/benlepsch/benbot-rs:${{ needs.create-tag.outputs.tag }}
          build-args: |
            git_sha=${{ github.sha }}
